<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://itq.edu/soa" targetNamespace="http://itq.edu/soa">
	
	<wsdl:types>
		<xs:schema targetNamespace="http://itq.edu/soa" elementFormDefault="qualified">
			<xs:include schemaLocation="DigitalServices.xsd"/>
		</xs:schema>
	</wsdl:types>
	
	<wsdl:message name="DigitalServicesMessageRequest">
		<wsdl:part name="parameter" element="tns:Request"/>
	</wsdl:message>
	
	<wsdl:message name="DigitalServicesMessageResponse">
		<wsdl:part name="parameter" element="tns:Response"/>
	</wsdl:message>
	
	<wsdl:portType name="DigitalServicesPortType">
		<wsdl:operation name="DigitalServicesOperation">
			<wsdl:input message="tns:DigitalServicesMessageRequest"/>
			<wsdl:output message="tns:DigitalServicesMessageResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="DigitalServicesBinding" type="tns:DigitalServicesPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<wsdl:operation name="DigitalServicesOperation">
			<soap:operation soapAction="http://itq.edu/soa/DigitalServicesOperation"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="DigitalServicesService">
		<wsdl:port name="DigitalServicesPort" binding="tns:DigitalServicesBinding">
			<soap:address location="http://localhost:8080/DigitalServices"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
